### ISSUE TITLE
Getting a sell and buy notification for the same pair

### ISSUE THREAD

**Issue by timh77** [ptnotifications/ptnotifications#8] opened 2018-04-22 11:08 UTC
This pair was just sold but got two notifications, one for the sell and a second for a buy. The buy didn't happen.
Also the sell rate is invalid. The buy message shows the correct one.

![telegram](https://user-images.githubusercontent.com/14058767/39094327-12ad4ccc-462e-11e8-894e-57e52dafa89e.JPG)

**Comment by smoochy** [comment] 2018-04-22 13:08
See https://github.com/Roy4lz/ptnotifications/issues/4

**Comment by thoeve** [comment] 2018-04-23 13:28
Duplicate of #4

**Closed as completed by thoeve** 2018-04-23 13:28 UTC
Labels: duplicate
